/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-07-04 09:03:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(12);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.5.RELEASE.jar", Long.valueOf(1654661316929L));
    _jspx_dependants.put("/WEB-INF/views/product/../header.jsp", Long.valueOf(1656031493803L));
    _jspx_dependants.put("/WEB-INF/views/product/../footer.jsp", Long.valueOf(1656031493802L));
    _jspx_dependants.put("/WEB-INF/views/product/sub_menu.html", Long.valueOf(1656039209160L));
    _jspx_dependants.put("/WEB-INF/views/product/comment.jsp", Long.valueOf(1656919120045L));
    _jspx_dependants.put("/WEB-INF/views/product/sub_img.html", Long.valueOf(1656039209162L));
    _jspx_dependants.put("jar:file:/D:/SpringWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/21_ShopMall/WEB-INF/lib/spring-webmvc-5.2.5.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1585016652000L));
    _jspx_dependants.put("jar:file:/D:/SpringWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/21_ShopMall/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/D:/SpringWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/21_ShopMall/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/D:/SpringWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/21_ShopMall/WEB-INF/lib/spring-webmvc-5.2.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1585016652000L));
    _jspx_dependants.put("jar:file:/D:/SpringWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/21_ShopMall/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1655957840863L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Nonage Shop</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/shopping.css\" >  \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery-3.6.0.min.js\"></script> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"member/member.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"product/product.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"member/findIdAndPassword.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"mypage/mypage.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("<!--헤더파일 들어가는 곳 시작 -->\r\n");
      out.write("  <header>\r\n");
      out.write("    <!--로고 들어가는 곳 시작--->  \r\n");
      out.write("    <div id=\"logo\">\r\n");
      out.write("      <a href=\"index\">\r\n");
      out.write("        <img src=\"images/logo.gif	\" width=\"180\" height=\"100\" alt=\"nonageshop\">\r\n");
      out.write("      </a>  \r\n");
      out.write("    </div>\r\n");
      out.write("    <!--로고 들어가는 곳 끝-->     \r\n");
      out.write("    <nav id=\"catagory_menu\">\r\n");
      out.write("     <ul>\r\n");
      out.write("       ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       <li>/</li>\r\n");
      out.write("       <li>\r\n");
      out.write("         <a href=\"cart_list\">CART</a>\r\n");
      out.write("       </li><li>/</li>\r\n");
      out.write("       <li>\r\n");
      out.write("         <a href=\"mypage\">MY PAGE</a>\r\n");
      out.write("       </li><li>/</li>\r\n");
      out.write("       <li>\r\n");
      out.write("         <a href=\"qna_list\">Q&amp;A(1:1)</a>\r\n");
      out.write("       </li>\r\n");
      out.write("     </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <nav id=\"top_menu\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"category?kind=1\">Heels</a>\r\n");
      out.write("        </li>  \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"category?kind=2\">Boots</a>\r\n");
      out.write("        </li>  \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"category?kind=3\">Sandals</a>\r\n");
      out.write("        </li> \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"category?kind=4\">Sneakers</a>\r\n");
      out.write("        </li> \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"category?kind=5\">On Sale</a>\r\n");
      out.write("        </li>  \r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"clear\"></div>\r\n");
      out.write("    <hr>\r\n");
      out.write("  </header>\r\n");
      out.write("  <!--헤더파일 들어가는 곳 끝 -->");
      out.write('\r');
      out.write('\n');
      out.write("<div id=\"sub_img\">\r\n");
      out.write("	<img src=\"images/product/sub_img.jpg\" >		\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>");
      out.write('\r');
      out.write('\n');
      out.write("  <nav id=\"sub_menu\">\r\n");
      out.write("    <ul>\r\n");
      out.write("	  <li><a href=\"category?kind=1\">Heels</a></li>  \r\n");
      out.write("	  <li><a href=\"category?kind=2\">Boots</a></li>  \r\n");
      out.write("	  <li><a href=\"category?kind=3\">Sandals</a></li> \r\n");
      out.write("	  <li><a href=\"category?kind=4\">Sneakers</a></li> \r\n");
      out.write("	  <li><a href=\"category?kind=5\"> On Sale</a></li> \r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("  <article>\r\n");
      out.write("    <h1> Item </h1>\r\n");
      out.write("    <div id=\"itemdetail\" >\r\n");
      out.write("      <form  method=\"post\" name=\"formm\" id=\"theform\">    \r\n");
      out.write("        <fieldset>\r\n");
      out.write("          <legend> Item detail Info</legend>  \r\n");
      out.write("          <a href=\"product_detail?pseq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.pseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">         \r\n");
      out.write("            <span style=\"float: left;\">\r\n");
      out.write("              <img src=\"product_images/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("            </span>              \r\n");
      out.write("            <h2> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </h2>  \r\n");
      out.write("          </a>    \r\n");
      out.write("          <label> 가 격 :  </label>  \r\n");
      out.write("          <p> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.price2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 원</p>  \r\n");
      out.write("          <label> 수 량 : </label>\r\n");
      out.write("          <input  type=\"text\"   name=\"quantity\" id=\"quantity\" size=\"2\"      value=\"1\"><br>\r\n");
      out.write("          <input  type=\"hidden\" name=\"pseq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.pseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <div id=\"buttons\">\r\n");
      out.write("          <input type=\"button\" value=\"장바구니에 담기\"   class=\"submit\"    onclick=\"go_cart()\"> \r\n");
      out.write("          <input type=\"button\" value=\"즉시 구매\"       class=\"submit\"    onclick=\"go_order()\"> \r\n");
      out.write("          <input type=\"reset\"  value=\"취소\"           class=\"cancel\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>  \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  <!-- 상품평 처리 -->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- link rel=\"stylesheet\" href=\"css/bootstrap.min.css\"> -->\r\n");
      out.write("    <style>\r\n");
      out.write("    #cCnt {\r\n");
      out.write("    	border-radius: 3px;\r\n");
      out.write("    	border: 1px solid #000;\r\n");
      out.write("    	padding: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #reply {\r\n");
      out.write("    	margin-top: 8px;\r\n");
      out.write("    	border-radius: 3px;\r\n");
      out.write("    	border: 1px solid #ccc;\r\n");
      out.write("    	padding: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    table#rep_input td{\r\n");
      out.write("    	border: 0px dotted;\r\n");
      out.write("    }\r\n");
      out.write("    .btn {\r\n");
      out.write("    	border: 1px solid #ccc;\r\n");
      out.write("    	border-radius: 3px;\r\n");
      out.write("    	background: #f00;\r\n");
      out.write("    	color: #fff;\r\n");
      out.write("    	padding: 5px;\r\n");
      out.write("    	margin: 0 5px;\r\n");
      out.write("    }\r\n");
      out.write("    #commentList {\r\n");
      out.write("    	background-color: rgba(254, 206, 229, 0.3);\r\n");
      out.write("    	border-radius: 3px;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <form id=\"commentForm\" name=\"commentForm\" method=\"post\">\r\n");
      out.write("    <br><br>\r\n");
      out.write("        <div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <span><h3>상품평</h3></span> <span id=\"cCnt\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"reply\">\r\n");
      out.write("                <table id=\"rep_input\" style=\"width: 650px\">                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td style=\"width:80%;\">\r\n");
      out.write("                            <textarea  rows=\"3\" cols=\"75\" id=\"content\" name=\"content\" placeholder=\"댓글을 입력하세요\"></textarea>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td style=\"width:10%;\">\r\n");
      out.write("                            <a href='#' onClick=\"save_comment('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.pseq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" class=\"btn\">등록</a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"hidden\" id=\"pseq\" name=\"pseq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.pseq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />        \r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <form id=\"commentListForm\" name=\"commentListForm\" method=\"post\">\r\n");
      out.write("        <div id=\"commentList\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("	<!-- 페이지 처리 영역 -->\r\n");
      out.write("    <div>\r\n");
      out.write("		<ul id=\"pagination\">\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		// 상품상세정보 로딩 시에 상품평 목록을 조회하여 출력\r\n");
      out.write("		getCommentList();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	// 상품평 목록 불러오기\r\n");
      out.write("	function getCommentList() {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type: 'GET',\r\n");
      out.write("			url: 'comments/list',\r\n");
      out.write("			dataType: 'json',\r\n");
      out.write("			data:$(\"#commentForm\").serialize(),\r\n");
      out.write("			contentType: 'application/x-www-form-urlencoded; charset=utf-8',\r\n");
      out.write("			success: function(data) {\r\n");
      out.write("				var pageMaker = data.pageInfo;\r\n");
      out.write("				var totalCount = data.total;\r\n");
      out.write("				var commentList = data.commentList;\r\n");
      out.write("				\r\n");
      out.write("				showHTML(pageMaker, commentList, totalCount);\r\n");
      out.write("			},\r\n");
      out.write("			error: function() {\r\n");
      out.write("				alert(\"상품평 목록을 조회하지 못했습니다.\")\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/*\r\n");
      out.write("	** 상품평 페이지별 목록 요청\r\n");
      out.write("	*/\r\n");
      out.write("	function getCommentPaging(pagenum, rowsperpage, pseq) {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type: 'GET',\r\n");
      out.write("			url: 'comments/list',\r\n");
      out.write("			dataType: 'json',\r\n");
      out.write("			data:{\"pageNum\": pagenum,\r\n");
      out.write("				  \"rowsPerPage\": rowsperpage,\r\n");
      out.write("				  \"pseq\": pseq},\r\n");
      out.write("			contentType: 'application/x-www-form-urlencoded; charset=utf-8',\r\n");
      out.write("			success: function(data) {\r\n");
      out.write("				var pageMaker = data.pageInfo;\r\n");
      out.write("				var totalCount = data.total;\r\n");
      out.write("				var commentList = data.commentList;\r\n");
      out.write("				console.log(\"pageMaker=\", pageMaker);\r\n");
      out.write("				console.log(\"count=\", totalCount);\r\n");
      out.write("				console.log(\"comments=\", commentList);\r\n");
      out.write("				\r\n");
      out.write("				showHTML(pageMaker, commentList, totalCount);\r\n");
      out.write("			},\r\n");
      out.write("			error: function() {\r\n");
      out.write("				alert(\"상품평 목록을 조회하지 못했습니다.\")\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function showHTML(pageMaker, commentList, totalCount) {\r\n");
      out.write("		var html = \"\";\r\n");
      out.write("		var p_html = \"\";\r\n");
      out.write("		\r\n");
      out.write("		if (commentList.length > 0) {\r\n");
      out.write("			// 상품평의 각 항목별로 HTML 생성\r\n");
      out.write("			$.each(commentList, function(index, item){\r\n");
      out.write("				html += \"<div>\";\r\n");
      out.write("				html += \"<div id=\\\"comment_item\\\"> <strong>작성자: \" + item.writer + \"</strong>\";\r\n");
      out.write("				html += \"<span id=\\\"write_date\\\">\" + displayTime(item.regDate) + \"</span><br>\";\r\n");
      out.write("				html += item.content+\"<br></div>\";\r\n");
      out.write("				html += \"</div>\";\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 페이징 버튼 출력\r\n");
      out.write("			if (pageMaker.prev == true) {\r\n");
      out.write("				p_html += \"<li class=\\\"paginate_button previous\\\">\";\r\n");
      out.write("				p_html += \"<a href='javascript:getCommentPaging(\"\r\n");
      out.write("					  +pageMaker.startPage-1+\",\"+pageMaker.criteria.rowsPerPage+\",\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.pseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+\")'>[이전]</a></li>\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			for(var i=pageMaker.startPage; i<=pageMaker.endPage; i++){\r\n");
      out.write("				p_html += \"<a href='javascript:getCommentPaging(\"\r\n");
      out.write("					  + i +\",\"+pageMaker.criteria.rowsPerPage+\",\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.pseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+\")'>[\"+i+\"]</a></li>\";\r\n");
      out.write("				console.log(p_html);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if (pageMaker.next == true) {\r\n");
      out.write("				p_html += \"<li class=\\\"paginate_button next\\\">\";\r\n");
      out.write("				p_html += \"<a href='javascript:getCommentPaging(\"\r\n");
      out.write("					  +(pageMaker.endPage+1)+\",\"+pageMaker.criteria.rowsPerPage+\",\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVO.pseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+\")'>[다음]</a></li>\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		} else { // 조회된 상품평이 없을 경우\r\n");
      out.write("			html += \"<div>\";\r\n");
      out.write("			html += \"<h5>등록된 상품평이 없습니다.</h5>\";\r\n");
      out.write("			html += \"</div>\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// 상품평 갯수 출력\r\n");
      out.write("		$(\"#cCnt\").html(\"댓글 \" + \"<span style='color:#00f;'>\" + totalCount+\"</span>\");\r\n");
      out.write("		// 상품평 목록 출력\r\n");
      out.write("		$(\"#commentList\").html(html);\r\n");
      out.write("		// 페이징 버튼 출력\r\n");
      out.write("		$(\"#pagination\").html(p_html);\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/*\r\n");
      out.write("	** 입력 파라미터:\r\n");
      out.write("	**     timeValue - 상품평 등록 시간\r\n");
      out.write("	*/\r\n");
      out.write("	function displayTime(timeValue) {\r\n");
      out.write("		var today = new Date();\r\n");
      out.write("		\r\n");
      out.write("		// 현재시간에서 댓글등록시간을 빼줌\r\n");
      out.write("		var timeGap = today.getTime() - timeValue;\r\n");
      out.write("		\r\n");
      out.write("		// timeValue를 Date객체로 변환\r\n");
      out.write("		var dateObj = new Date(timeValue);\r\n");
      out.write("		\r\n");
      out.write("		// timeGap이 24시간 이내인지 판단\r\n");
      out.write("		if (timeGap < (1000 * 60 * 60 * 24)) {  // 시, 분, 초를 구함\r\n");
      out.write("			var hh = dateObj.getHours();\r\n");
      out.write("			var mi = dateObj.getMinutes();\r\n");
      out.write("			var ss = dateObj.getSeconds();\r\n");
      out.write("			\r\n");
      out.write("			//return hh + ':' + mi + ':' + ss;\r\n");
      out.write("			return [(hh>9 ? '':'0')+hh, ':', (mi>9 ? '':'0')+mi, ':', \r\n");
      out.write("				    (ss>9 ? '':'0')+ss].join('');\r\n");
      out.write("		} else {\r\n");
      out.write("			var yy = dateObj.getFullYear();\r\n");
      out.write("			var mm = dateObj.getMonth() + 1;\r\n");
      out.write("			var dd = dateObj.getDate();\r\n");
      out.write("			\r\n");
      out.write("			//return yy + \"-\" + mm + \"-\" + dd;\r\n");
      out.write("			return [yy, '/', (mm>9 ? '':'0')+mm, '/', (dd>9 ? '':'0')+dd].join('');\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/*\r\n");
      out.write("	** 상품 등록\r\n");
      out.write("	*/\r\n");
      out.write("	function save_comment(pseq) {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:'POST',\r\n");
      out.write("			url:'comments/save',\r\n");
      out.write("			data:$(\"#commentForm\").serialize(),\r\n");
      out.write("			success: function(data) {\r\n");
      out.write("				if (data=='success') {	// 상품평 등록 성공\r\n");
      out.write("					getCommentList(); 	// 상품평 목록 요청함수 호출\r\n");
      out.write("					$(\"#content\").val(\"\");\r\n");
      out.write("				} else if (data=='fail') {\r\n");
      out.write("					alert(\"상품평 등록이 실패하였습니다. 다시 시도해 주세요.\");\r\n");
      out.write("				} else if (data=='not_logedin') {\r\n");
      out.write("					alert(\"상품평 등록은 로그인이 필요합니다.\");\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function(request, status, error) {\r\n");
      out.write("				alert(\"error:\" + error);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  </article>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"clear\"></div>\r\n");
      out.write("    \r\n");
      out.write("  <footer>  \r\n");
      out.write("    <hr>\r\n");
      out.write("    <div id=\"copy\">\r\n");
      out.write("     All contents Copyright 2013 Nonage Inc. all rights reserved<br>\r\n");
      out.write("     Contact mail : Nonage@Nonage.com Tel: +82 64 123 4315 \r\n");
      out.write("     Fax +82 64 123 4321\r\n");
      out.write("    </div>         \r\n");
      out.write("  </footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("       ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("       ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("       \r\n");
          out.write("       ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/product/../header.jsp(32,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("       <li>         \r\n");
          out.write("         <a href=\"login_form\" style=\"width:110px;\">LOGIN(CUSTOMER</a>   \r\n");
          out.write("	     <a href=\"admin_login_form\" style=\"width:100px;\">| ADMIN)</a>\r\n");
          out.write("	   </li>		       \r\n");
          out.write("       <li>/</li>\r\n");
          out.write("       <li><a href=\"contract\">JOIN</a></li>\r\n");
          out.write("       ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("       <li style=\"color:orange\">\r\n");
          out.write("         ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\r\n");
          out.write("       </li>\r\n");
          out.write("       <li><a href=\"logout\">LOGOUT</a></li>\r\n");
          out.write("       ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
